// Copyright 2026 zankia mail@zankia.fr
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define ENCODER_MAP_ENABLE
#define AZOTEQ_IQS5XX_TPS65
#define AZOTEQ_IQS5XX_PRESS_AND_HOLD_ENABLE true
#define AZOTEQ_IQS5XX_HOLD_TIME 150
#define AZOTEQ_IQS5XX_TAP_DISTANCE 8
#define AZOTEQ_IQS5XX_SCROLL_INITIAL_DISTANCE 0
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#define POINTING_DEVICE_HIRES_SCROLL_MULTIPLIER 16
#define POINTING_DEVICE_HIRES_SCROLL_EXPONENT 1

